In [2]:
import numpy as np

X_train = np.array([[5, 6, 2, 3], [1, 2, 4, 2], [3, 2, 4, 4], [5, 6, 2, 3], [1, 2, 4, 2], [3, 2, 4, 4], [3, 2, 4, 4], [5, 6, 2, 3], [1, 2, 4, 2], [3, 2, 4, 4], [3, 2, 4, 4], [5, 6, 2, 3], [1, 2, 4, 2]])
X = np.array([[1, 2, 4, 7], [2, 3, 5, 1], [3, 4, 5, 3]])

In [34]:
def compute_distances_two_loops(X_train, X):
    """
    Compute the distance between each test point in X and each training point
    in self.X_train using a nested loop over both the training data and the 
    test data.

    Inputs:
    - X: A numpy array of shape (num_test, D) containing test data.

    Returns:
    - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
      is the Euclidean distance between the ith test point and the jth training
      point.
    """
    num_test = X.shape[0]
    num_train = X_train.shape[0]
    dists = np.zeros((num_test, num_train))
    for i in range(num_test):
      for j in range(num_train):
        dists[i, j] = np.sum((X[i] - X_train[j])**2)**.5
        #####################################################################
        # TODO:                                                             #
        # Compute the l2 distance between the ith test point and the jth    #
        # training point, and store the result in dists[i, j]. You should   #
        # not use a loop over dimension.                                    #
        #####################################################################
        pass
        #####################################################################
        #                       END OF YOUR CODE                            #
        #####################################################################
    return dists

def compute_distances_no_loops(X_train, X):
    """
    Compute the distance between each test point in X and each training point
    in self.X_train using no explicit loops.

    Input / Output: Same as compute_distances_two_loops
    """
    num_test = X.shape[0]
    num_train = X_train.shape[0]
    dists = np.zeros((num_test, num_train))

    # a^2 - 2ab + b^2 = (a - b)^2, now we will calculate -2ab
    dists = np.dot(X, X_train.T) * (-2)
    test_sq_sum = np.sum(X**2, axis=1)
    train_sq_sum = np.sum(X_train**2, axis=1)
    
    print(test_sq_sum)
    print(train_sq_sum)
    
    # adding the a^2 and b^2 terms
    print(dists)
    dists = (dists.T + test_sq_sum.T).T
    print()
    print(dists)
    dists += train_sq_sum
    print()
    print(dists)
    dists = np.sqrt(dists)
    
    return dists



print(X.shape, X_train.shape)

dists = compute_distances_no_loops(X_train, X)
print(dists)
print(dists.shape)

(3, 4) (13, 4)
[70 39 59]
[74 25 45 74 25 45 45 74 25 45 45 74 25]
[[ -92  -70 -102  -92  -70 -102 -102  -92  -70 -102 -102  -92  -70]
 [ -82  -60  -72  -82  -60  -72  -72  -82  -60  -72  -72  -82  -60]
 [-116  -74  -98 -116  -74  -98  -98 -116  -74  -98  -98 -116  -74]]

[[-22   0 -32 -22   0 -32 -32 -22   0 -32 -32 -22   0]
 [-43 -21 -33 -43 -21 -33 -33 -43 -21 -33 -33 -43 -21]
 [-57 -15 -39 -57 -15 -39 -39 -57 -15 -39 -39 -57 -15]]

[[52 25 13 52 25 13 13 52 25 13 13 52 25]
 [31  4 12 31  4 12 12 31  4 12 12 31  4]
 [17 10  6 17 10  6  6 17 10  6  6 17 10]]
[[7.21110255 5.         3.60555128 7.21110255 5.         3.60555128
  3.60555128 7.21110255 5.         3.60555128 3.60555128 7.21110255
  5.        ]
 [5.56776436 2.         3.46410162 5.56776436 2.         3.46410162
  3.46410162 5.56776436 2.         3.46410162 3.46410162 5.56776436
  2.        ]
 [4.12310563 3.16227766 2.44948974 4.12310563 3.16227766 2.44948974
  2.44948974 4.12310563 3.16227766 2.44948974 2.44948974 4.123105

In [4]:
((5-1)**2 + 4**2 + 2**2 + 4**2)**.5

7.211102550927978

In [5]:
np.sum(X, axis=1)

array([14, 11, 15])